version: '3.8'

services:

  redis-db:
    image: redis:8.10.1-alpine
    container_name: redis_container

    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    command: redis-server /usr/local/etc/redis/redis.conf

    restart: always

  spring-app:
    build: .
    container_name: spring_app_container
    ports:
      - "127.0.0.1:16767:8080" # убрано тк не нужно пока что

    depends_on:
      - redis-db
    environment:
      - SPRING_DATA_REDIS_HOST=redis-db
      - SPRING_DATA_REDIS_PORT=6379
    restart: on-failure

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - spring-app
    restart: always

volumes:
  redis_data: 
  caddy_data: 
  caddy_config: 