bind 0.0.0.0
port 6379

# Защищенный режим. Если включен (yes) и не заданы пароли/интерфейсы, Redis будет отвечать только на запросы с локальной машины.
protected-mode no

# AOF (возможно поменяю на RDB, хз пока)
appendonly yes
appendfsync everysec

# Максимальный объем памяти, который Redis может использовать. Когда этот лимит достигнут, Redis будет применять политику вытеснения данных (maxmemory-policy).
# maxmemory: 8mb
# Политика вытеснения данных при нехватке памяти:noeviction: возвращает ошибку при попытке записи новых данных.allkeys-lru: удаляет наименее используемые ключи (LRU) среди всей базы.volatile-lru: удаляет наименее используемые ключи только среди тех, у которых задан срок жизни (TTL).
maxmemory-policy allkeys-lru

# Количество баз данных, доступных в Redis. По умолчанию 16 (от 0 до 15).
# databases: 16