name: Deploy Nuxt to GitHub Pages

on:
  push:
    branches:
      - main # Или укажите вашу рабочую ветку (например, web, если пишете на ней)

# Разрешения для работы с GitHub Pages внутри пайплайна
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Укажите используемую вами версию Node.js
          cache: 'npm' # Измените на yarn/pnpm при необходимости
          cache-dependency-path: nosql-sem5-lab1-frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./nosql-sem5-lab1-frontend
        run: npm ci

      - name: Static HTML Generation
        working-directory: ./nosql-sem5-lab1-frontend
        run: npx nuxt generate # Генерирует статику в папку .output/public

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./nosql-sem5-lab1-frontend/.output/public"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4    cache-dependency-path: nosql-sem5-lab1-frontend/package-lock.json